name: CI
on:
  pull_request:
    branches: [develop, main]
jobs:
  linTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install dependencies
        run: npm install
      - name: Security Check
        run: npm audit
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
  
